### PR TITLE
:seedling: Refactor client certificate

### PR DESCRIPTION
**Pull request by xuezhaojun**
## Summary

* Remove the function `HasValidHubKubeconfig` since it's not used anymore.
* Print more information in `shouldCreateCSR` function.

### CODE REVIEW

**Comment by xuezhaojun** [comment]
/assign @elgnay 

Please take a review when you have time, thanks!

**Comment by qiujian16** [comment]
/hold
@elgnay this may conflict with the PR that remove additionalDataSensitive flag?

**Comment by xuezhaojun** [comment]
@qiujian16  code rebased, please take another review.

**Pull request merged**
