### PR TITLE
:seedling: Remove unnecessary code for removing managed cluster resources

### PR DESCRIPTION
**Pull request by xuezhaojun**
## Summary

When hubAcceptsClient toggle between `true` and `false`, we want to keep the resources.

The resources we want to keep are:

```go
        // Hub cluster-admin accepts the spoke cluster, we apply
	// 1. clusterrole and clusterrolebinding for this spoke cluster.
	// 2. namespace for this spoke cluster.
	// 3. role and rolebinding for this spoke cluster on its namespace.
	resourceResults := c.applier.Apply(
		ctx,
		syncCtx.Recorder(),
		helpers.ManagedClusterAssetFn(manifests.RBACManifests, managedClusterName),
		staticFiles...,
	)
```

If the namespace of the spoke cluster removed, then all manifestwork applied in that namespace will also gone. We want to avoid that.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by qiujian16** [comment]
hrm I do not thin we remove ns right now... @skeeey ?

**Comment by skeeey** [comment]
we will keep the ns when a managed cluster is denied, https://github.com/open-cluster-management-io/ocm/blob/main/pkg/registration/hub/managedcluster/controller.go#L31

**Comment by skeeey** [comment]
we may, but it's difficult to handle the namespace, because there are too many cases we need consider (like the acm import controller does)

**Pull request closed without merging**
