### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dockerymick**
Small proposal for consistency

### CODE REVIEW

**Comment by mikeshng** [comment]
@dockerymick thank you for your contribution!

Could you please run
`git commit -s --amend` then `git push -f .......` 

/assign @dhaiducek
/assign @mprahl

**Comment by dockerymick** [comment]
@mikeshng this is what I received 
Screen Shot 2022-07-21 at 10 31 11 AM

**Comment by dockerymick** [comment]
@mikeshng this is what I received 
Screen Shot 2022-07-21 at 10 31 11 AM

**Comment by dhaiducek** [comment]
I think that's expected since we don't have permissions for this repo. Try this to add your fork and push to it instead:
```
git remote add dockerymick https://github.com/dockerymick/OCM
git push --set-upstream dockermick patch-1
```

It'll probably reject it since the commits are different, but then you can try
```
git push -f
```

**Comment by mikeshng** [comment]
@dockerymick I think you need to do the following: 
```
git clone git@github.com:dockerymick/OCM.git # If you don't have your fork already cloned
git checkout patch-1
git log
```
you should see
```
commit 0c154560989d71b48c65aa72e34d9d453b721a5e (HEAD -> patch-1, origin/patch-1)
Author: Mikela Jackson <mdockery@redhat.com>
Date:   Thu Jul 21 10:19:57 2022 -0400

    Update README.md
    
    Small proposal for consistency

commit e0322bd1c7fc403dafefe42652fe8cf4c7ea32d9 (origin/main, origin/HEAD, main)
....
```

then you run
```
git commit -s --amend
git push -f origin patch-1
```

**Comment by dockerymick** [comment]
Screen Shot 2022-07-21 at 11 50 53 AM


I am going to close this and retry

**Pull request closed without merging**
