### PR TITLE
:seedling: remove ClusterSet ClusterSetBinding API version v1beta1

### PR DESCRIPTION
**Pull request by haoqing0110**
## Summary
https://github.com/open-cluster-management-io/ocm/issues/67

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by haoqing0110** [comment]
/assign @qiujian16 
This PR updates the API dependency and CRDs, including the rollout strategy change in [manifestworkreplicasets](https://github.com/open-cluster-management-io/ocm/pull/257/files#diff-b48ce88c54feadef4fbe798690f0fb66fe88dbb4cc1f1d51eeaf85cb7dc11b83), could you help review if it is OK to update it in OCM repo?

**Comment by qiujian16** [comment]
please note the codecov is reduced

**Pull request merged**
