### PR TITLE
:seedling: Update the OCM/API denpendency.

### PR DESCRIPTION
**Pull request by xuezhaojun**
## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by qiujian16** [comment]
cc @haoqing0110 this relates to the rollout

**Comment by xuezhaojun** [comment]
> cc @haoqing0110 this relates to the rollout

The related PR: https://github.com/open-cluster-management-io/api/pull/281 Please take a look! Thanks!

**Comment by xuezhaojun** [comment]
Overlap with this PR: https://github.com/open-cluster-management-io/ocm/pull/310

**Pull request closed without merging**
