### PR TITLE
Remove build-info metrics.

### PR DESCRIPTION
**Pull request by xuezhaojun**
Fixes: https://kubernetes.slack.com/archives/C01GE7YSUUF/p1685471619923169

### CODE REVIEW

**Comment by xuezhaojun** [comment]
The work integration fix is on-going https://github.com/open-cluster-management-io/ocm/pull/150, this one can be merged first.

**Comment by qiujian16** [comment]
integration fails...

**Comment by xuezhaojun** [comment]
Change is included in another PR.
/close

**Pull request closed without merging**
