### PR TITLE
:bug: Fix: using ownerRef to control the removal of storageversionmigrations.

### PR DESCRIPTION
**Pull request by xuezhaojun**
## Summary

When create a StorageVersionMigration, using the cluster-manager as the ownerReference. When cluster-manager is removed, all Migrations will also be removed.

## Related issue(s)

Previously, it uses a remove function that depending on:

https://github.com/open-cluster-management-io/ocm/blob/40135fd4baf762630ffc161b6341837081dc05c0/pkg/operator/operators/clustermanager/controllers/migrationcontroller/migration_controller.go#L52

From release to release the files list are changed, but during the upgrade the cluster-manager keep exisitng, so that old storageversionmigration CRs won't get removed ever.

Fixes #

### CODE REVIEW

**Comment by qiujian16** [comment]
but the clustermanager will not be removed during upgrade, only uninstall will remove cluster manager. Is it what you are expecting?

**Comment by xuezhaojun** [comment]
> but the clustermanager will not be removed during upgrade, only uninstall will remove cluster manager. Is it what you are expecting?

Yes, keep them won't harm anything.  This PR just make sure when we uninstall clustermanager, everything we installed will be cleaned up.

**Pull request merged**
