### PR TITLE
:seedling: return raw data of chart render results

### PR DESCRIPTION
**Pull request by zhiweiyin318**
## Summary
update operator charts render function to return raw data of the results.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by xuezhaojun** [comment]
Can we add the motivation of this PR? Like improve performance?

**Comment by zhiweiyin318** [comment]
> Can we add the motivation of this PR? Like improve performance?

@xuezhaojun  to return raw data will be easy for other components to consume, like clusteradm .

**Review by qiujian16 — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
